Ok I added the following options to configure.ac   --with-ssl=PFX        Path to ssl files   --with-libjpeg=PFX    Path to libjpeg files   --with-libpng=PFX     Path to libpng files   --with-libz=PFX       Path to libz files   --with-mozilla=PFX    Path to mozilla files (The mozilla one still needs some work but its a start)
I also cleaned up the blender/intern automake files a little as far as
the python stuff goes, it still isn't doing the correct thing in
intern/python/freeze but its a little closer I think.

Anyone that has ideas on this I'm all ears :)

Kent
--
mein@cs.umn.edu


git-svn-id: https://svn.blender.org/svnroot/bf-blender/trunk@115 954f8c5b-7b00-dc11-b283-0030488c597c

diff --git a/blender/configure b/blender/configure
--- a/blender/configure
+++ b/blender/configure
@@ -1035,6 +1035,11 @@ Optional Packages:
   --with-pic              try to use only PIC/non-PIC objects default=use both
   --with-cxxflags         Override default compiler flags
   --with-gameblender      Build game engine (default=without)
+  --with-ssl=PFX        Path to ssl files
+  --with-libjpeg=PFX    Path to libjpeg files
+  --with-libpng=PFX     Path to libpng files
+  --with-libz=PFX       Path to libz files
+  --with-mozilla=PFX    Path to mozilla files
   --with-x                use the X Window System
 
 Some influential environment variables:
@@ -4726,7 +4731,7 @@ test "x$enable_libtool_lock" != xno && enable_libtool_lock=yes
 case $host in
 *-*-irix6*)
   # Find out which ABI we are using.
-  echo '#line 4729 "configure"' > conftest.$ac_ext
+  echo '#line 4734 "configure"' > conftest.$ac_ext
   if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
   (eval $ac_compile) 2>&5
   ac_status=$?
@@ -5244,7 +5249,7 @@ chmod -w .
 save_CFLAGS="$CFLAGS"
 CFLAGS="$CFLAGS -o out/conftest2.$ac_objext"
 compiler_c_o=no
-if { (eval echo configure:5247: \"$ac_compile\") 1>&5; (eval $ac_compile) 2>out/conftest.err; } && test -s out/conftest2.$ac_objext; then
+if { (eval echo configure:5252: \"$ac_compile\") 1>&5; (eval $ac_compile) 2>out/conftest.err; } && test -s out/conftest2.$ac_objext; then
   # The compiler can only warn and ignore the option if not recognized
   # So say no if there are warnings
   if test -s out/conftest.err; then
@@ -6989,7 +6994,7 @@ else
     lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 6992 "configure"
+#line 6997 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -7087,7 +7092,7 @@ else
     lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 7090 "configure"
+#line 7095 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -8039,6 +8044,77 @@ if test "${with_gameblender+set}" = set; then
 else
       with_gameblender=no
 fi;
+
+
+# Check whether --with-ssl or --without-ssl was given.
+if test "${with_ssl+set}" = set; then
+  withval="$with_ssl"
+         if test $withval != "yes"; then
+		with_ssl =$withval
+	fi
+	if test x$with_ssl != "yes"; then
+           LDFLAGS="$LDFLAGS -L$withval/lib -lssl"
+           CPPFLAGS="$CPPFLAGS -I$withval/include"
+	fi
+
+fi;
+
+
+# Check whether --with-libjpeg or --without-libjpeg was given.
+if test "${with_libjpeg+set}" = set; then
+  withval="$with_libjpeg"
+         if test $withval != "yes"; then
+                with_libjpeg =$withval
+        fi
+        if test x$with_libjpeg != "yes"; then
+           LDFLAGS="$LDFLAGS -L$withval/lib -ljpeg"
+           CPPFLAGS="$CPPFLAGS -I$withval/include"
+        fi
+
+fi;
+
+
+# Check whether --with-libpng or --without-libpng was given.
+if test "${with_libpng+set}" = set; then
+  withval="$with_libpng"
+         if test $withval != "yes"; then
+                with_libpng =$withval
+        fi
+        if test x$with_libpng != "yes"; then
+           LDFLAGS="$LDFLAGS -L$withval/lib -lpng"
+           CPPFLAGS="$CPPFLAGS -I$withval/include"
+        fi
+
+fi;
+
+
+# Check whether --with-libz or --without-libz was given.
+if test "${with_libz+set}" = set; then
+  withval="$with_libz"
+         if test $withval != "yes"; then
+                with_libz =$withval
+        fi
+        if test x$with_libz != "yes"; then
+           LDFLAGS="$LDFLAGS -L$withval/lib -lz"
+           CPPFLAGS="$CPPFLAGS -I$withval/include"
+        fi
+
+fi;
+
+
+# Check whether --with-mozilla or --without-mozilla was given.
+if test "${with_mozilla+set}" = set; then
+  withval="$with_mozilla"
+         if test $withval != "yes"; then
+                with_mozilla =$withval
+        fi
+        if test x$with_mozilla != "yes"; then
+           LDFLAGS="$LDFLAGS -L$withval/lib/mozilla-$MOZVER -lnspr"
+           CPPFLAGS="$CPPFLAGS -I$withval/include/mozilla-$MOZVER/nspr",
+        fi
+
+fi;
+
 
 #Refactor sound lib options.
   # Check whether --enable-openal or --disable-openal was given.
@@ -10452,6 +10528,212 @@ else
 fi
 echo "$as_me:$LINENO: result: $ac_cv_header_GL_glu_h" >&5
 echo "${ECHO_T}$ac_cv_header_GL_glu_h" >&6
+
+fi
+
+
+  if test "${ac_cv_header__System_Library_Frameworks_OpenGL_framework_Versions_A_Headers_gl_h+set}" = set; then
+  echo "$as_me:$LINENO: checking for /System/Library/Frameworks/OpenGL.framework/Versions/A/Headers/gl.h" >&5
+echo $ECHO_N "checking for /System/Library/Frameworks/OpenGL.framework/Versions/A/Headers/gl.h... $ECHO_C" >&6
+if test "${ac_cv_header__System_Library_Frameworks_OpenGL_framework_Versions_A_Headers_gl_h+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+fi
+echo "$as_me:$LINENO: result: $ac_cv_header__System_Library_Frameworks_OpenGL_framework_Versions_A_Headers_gl_h" >&5
+echo "${ECHO_T}$ac_cv_header__System_Library_Frameworks_OpenGL_framework_Versions_A_Headers_gl_h" >&6
+else
+  # Is the header compilable?
+echo "$as_me:$LINENO: checking /System/Library/Frameworks/OpenGL.framework/Versions/A/Headers/gl.h usability" >&5
+echo $ECHO_N "checking /System/Library/Frameworks/OpenGL.framework/Versions/A/Headers/gl.h usability... $ECHO_C" >&6
+cat >conftest.$ac_ext <<_ACEOF
+#line $LINENO "configure"
+#include "confdefs.h"
+$ac_includes_default
+#include </System/Library/Frameworks/OpenGL.framework/Versions/A/Headers/gl.h>
+_ACEOF
+rm -f conftest.$ac_objext
+if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
+  (eval $ac_compile) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+         { ac_try='test -s conftest.$ac_objext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  ac_header_compiler=yes
+else
+  echo "$as_me: failed program was:" >&5
+cat conftest.$ac_ext >&5
+ac_header_compiler=no
+fi
+rm -f conftest.$ac_objext conftest.$ac_ext
+echo "$as_me:$LINENO: result: $ac_header_compiler" >&5
+echo "${ECHO_T}$ac_header_compiler" >&6
+
+# Is the header present?
+echo "$as_me:$LINENO: checking /System/Library/Frameworks/OpenGL.framework/Versions/A/Headers/gl.h presence" >&5
+echo $ECHO_N "checking /System/Library/Frameworks/OpenGL.framework/Versions/A/Headers/gl.h presence... $ECHO_C" >&6
+cat >conftest.$ac_ext <<_ACEOF
+#line $LINENO "configure"
+#include "confdefs.h"
+#include </System/Library/Frameworks/OpenGL.framework/Versions/A/Headers/gl.h>
+_ACEOF
+if { (eval echo "$as_me:$LINENO: \"$ac_cpp conftest.$ac_ext\"") >&5
+  (eval $ac_cpp conftest.$ac_ext) 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } >/dev/null; then
+  if test -s conftest.err; then
+    ac_cpp_err=$ac_c_preproc_warn_flag
+  else
+    ac_cpp_err=
+  fi
+else
+  ac_cpp_err=yes
+fi
+if test -z "$ac_cpp_err"; then
+  ac_header_preproc=yes
+else
+  echo "$as_me: failed program was:" >&5
+  cat conftest.$ac_ext >&5
+  ac_header_preproc=no
+fi
+rm -f conftest.err conftest.$ac_ext
+echo "$as_me:$LINENO: result: $ac_header_preproc" >&5
+echo "${ECHO_T}$ac_header_preproc" >&6
+
+# So?  What about this header?
+case $ac_header_compiler:$ac_header_preproc in
+  yes:no )
+    { echo "$as_me:$LINENO: WARNING: /System/Library/Frameworks/OpenGL.framework/Versions/A/Headers/gl.h: accepted by the compiler, rejected by the preprocessor!" >&5
+echo "$as_me: WARNING: /System/Library/Frameworks/OpenGL.framework/Versions/A/Headers/gl.h: accepted by the compiler, rejected by the preprocessor!" >&2;}
+    { echo "$as_me:$LINENO: WARNING: /System/Library/Frameworks/OpenGL.framework/Versions/A/Headers/gl.h: proceeding with the preprocessor's result" >&5
+echo "$as_me: WARNING: /System/Library/Frameworks/OpenGL.framework/Versions/A/Headers/gl.h: proceeding with the preprocessor's result" >&2;};;
+  no:yes )
+    { echo "$as_me:$LINENO: WARNING: /System/Library/Frameworks/OpenGL.framework/Versions/A/Headers/gl.h: present but cannot be compiled" >&5
+echo "$as_me: WARNING: /System/Library/Frameworks/OpenGL.framework/Versions/A/Headers/gl.h: present but cannot be compiled" >&2;}
+    { echo "$as_me:$LINENO: WARNING: /System/Library/Frameworks/OpenGL.framework/Versions/A/Headers/gl.h: check for missing prerequisite headers?" >&5
+echo "$as_me: WARNING: /System/Library/Frameworks/OpenGL.framework/Versions/A/Headers/gl.h: check for missing prerequisite headers?" >&2;}
+    { echo "$as_me:$LINENO: WARNING: /System/Library/Frameworks/OpenGL.framework/Versions/A/Headers/gl.h: proceeding with the preprocessor's result" >&5
+echo "$as_me: WARNING: /System/Library/Frameworks/OpenGL.framework/Versions/A/Headers/gl.h: proceeding with the preprocessor's result" >&2;};;
+esac
+echo "$as_me:$LINENO: checking for /System/Library/Frameworks/OpenGL.framework/Versions/A/Headers/gl.h" >&5
+echo $ECHO_N "checking for /System/Library/Frameworks/OpenGL.framework/Versions/A/Headers/gl.h... $ECHO_C" >&6
+if test "${ac_cv_header__System_Library_Frameworks_OpenGL_framework_Versions_A_Headers_gl_h+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  ac_cv_header__System_Library_Frameworks_OpenGL_framework_Versions_A_Headers_gl_h=$ac_header_preproc
+fi
+echo "$as_me:$LINENO: result: $ac_cv_header__System_Library_Frameworks_OpenGL_framework_Versions_A_Headers_gl_h" >&5
+echo "${ECHO_T}$ac_cv_header__System_Library_Frameworks_OpenGL_framework_Versions_A_Headers_gl_h" >&6
+
+fi
+
+
+  if test "${ac_cv_header__System_Library_Frameworks_OpenGL_framework_Versions_A_Headers_glu_h+set}" = set; then
+  echo "$as_me:$LINENO: checking for /System/Library/Frameworks/OpenGL.framework/Versions/A/Headers/glu.h" >&5
+echo $ECHO_N "checking for /System/Library/Frameworks/OpenGL.framework/Versions/A/Headers/glu.h... $ECHO_C" >&6
+if test "${ac_cv_header__System_Library_Frameworks_OpenGL_framework_Versions_A_Headers_glu_h+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+fi
+echo "$as_me:$LINENO: result: $ac_cv_header__System_Library_Frameworks_OpenGL_framework_Versions_A_Headers_glu_h" >&5
+echo "${ECHO_T}$ac_cv_header__System_Library_Frameworks_OpenGL_framework_Versions_A_Headers_glu_h" >&6
+else
+  # Is the header compilable?
+echo "$as_me:$LINENO: checking /System/Library/Frameworks/OpenGL.framework/Versions/A/Headers/glu.h usability" >&5
+echo $ECHO_N "checking /System/Library/Frameworks/OpenGL.framework/Versions/A/Headers/glu.h usability... $ECHO_C" >&6
+cat >conftest.$ac_ext <<_ACEOF
+#line $LINENO "configure"
+#include "confdefs.h"
+$ac_includes_default
+#include </System/Library/Frameworks/OpenGL.framework/Versions/A/Headers/glu.h>
+_ACEOF
+rm -f conftest.$ac_objext
+if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
+  (eval $ac_compile) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+         { ac_try='test -s conftest.$ac_objext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  ac_header_compiler=yes
+else
+  echo "$as_me: failed program was:" >&5
+cat conftest.$ac_ext >&5
+ac_header_compiler=no
+fi
+rm -f conftest.$ac_objext conftest.$ac_ext
+echo "$as_me:$LINENO: result: $ac_header_compiler" >&5
+echo "${ECHO_T}$ac_header_compiler" >&6
+
+# Is the header present?
+echo "$as_me:$LINENO: checking /System/Library/Frameworks/OpenGL.framework/Versions/A/Headers/glu.h presence" >&5
+echo $ECHO_N "checking /System/Library/Frameworks/OpenGL.framework/Versions/A/Headers/glu.h presence... $ECHO_C" >&6
+cat >conftest.$ac_ext <<_ACEOF
+#line $LINENO "configure"
+#include "confdefs.h"
+#include </System/Library/Frameworks/OpenGL.framework/Versions/A/Headers/glu.h>
+_ACEOF
+if { (eval echo "$as_me:$LINENO: \"$ac_cpp conftest.$ac_ext\"") >&5
+  (eval $ac_cpp conftest.$ac_ext) 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } >/dev/null; then
+  if test -s conftest.err; then
+    ac_cpp_err=$ac_c_preproc_warn_flag
+  else
+    ac_cpp_err=
+  fi
+else
+  ac_cpp_err=yes
+fi
+if test -z "$ac_cpp_err"; then
+  ac_header_preproc=yes
+else
+  echo "$as_me: failed program was:" >&5
+  cat conftest.$ac_ext >&5
+  ac_header_preproc=no
+fi
+rm -f conftest.err conftest.$ac_ext
+echo "$as_me:$LINENO: result: $ac_header_preproc" >&5
+echo "${ECHO_T}$ac_header_preproc" >&6
+
+# So?  What about this header?
+case $ac_header_compiler:$ac_header_preproc in
+  yes:no )
+    { echo "$as_me:$LINENO: WARNING: /System/Library/Frameworks/OpenGL.framework/Versions/A/Headers/glu.h: accepted by the compiler, rejected by the preprocessor!" >&5
+echo "$as_me: WARNING: /System/Library/Frameworks/OpenGL.framework/Versions/A/Headers/glu.h: accepted by the compiler, rejected by the preprocessor!" >&2;}
+    { echo "$as_me:$LINENO: WARNING: /System/Library/Frameworks/OpenGL.framework/Versions/A/Headers/glu.h: proceeding with the preprocessor's result" >&5
+echo "$as_me: WARNING: /System/Library/Frameworks/OpenGL.framework/Versions/A/Headers/glu.h: proceeding with the preprocessor's result" >&2;};;
+  no:yes )
+    { echo "$as_me:$LINENO: WARNING: /System/Library/Frameworks/OpenGL.framework/Versions/A/Headers/glu.h: present but cannot be compiled" >&5
+echo "$as_me: WARNING: /System/Library/Frameworks/OpenGL.framework/Versions/A/Headers/glu.h: present but cannot be compiled" >&2;}
+    { echo "$as_me:$LINENO: WARNING: /System/Library/Frameworks/OpenGL.framework/Versions/A/Headers/glu.h: check for missing prerequisite headers?" >&5
+echo "$as_me: WARNING: /System/Library/Frameworks/OpenGL.framework/Versions/A/Headers/glu.h: check for missing prerequisite headers?" >&2;}
+    { echo "$as_me:$LINENO: WARNING: /System/Library/Frameworks/OpenGL.framework/Versions/A/Headers/glu.h: proceeding with the preprocessor's result" >&5
+echo "$as_me: WARNING: /System/Library/Frameworks/OpenGL.framework/Versions/A/Headers/glu.h: proceeding with the preprocessor's result" >&2;};;
+esac
+echo "$as_me:$LINENO: checking for /System/Library/Frameworks/OpenGL.framework/Versions/A/Headers/glu.h" >&5
+echo $ECHO_N "checking for /System/Library/Frameworks/OpenGL.framework/Versions/A/Headers/glu.h... $ECHO_C" >&6
+if test "${ac_cv_header__System_Library_Frameworks_OpenGL_framework_Versions_A_Headers_glu_h+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  ac_cv_header__System_Library_Frameworks_OpenGL_framework_Versions_A_Headers_glu_h=$ac_header_preproc
+fi
+echo "$as_me:$LINENO: result: $ac_cv_header__System_Library_Frameworks_OpenGL_framework_Versions_A_Headers_glu_h" >&5
+echo "${ECHO_T}$ac_cv_header__System_Library_Frameworks_OpenGL_framework_Versions_A_Headers_glu_h" >&6
 
 fi
 
